name: CI/CD for Lambda
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      NPM_TOKEN:
        required: true
  push:
    branches:
      - 'main'
      - 'staging'
      - 'production'
    paths:
      - 'apps/lambda/**'
  pull_request:
    types:
      - 'labeled'
    branches:
      - 'main'
      - 'staging'
      - 'production'
    paths:
      - 'apps/lambda/**'
jobs:
  test:
    name: Execute Test
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'tested' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: '@dekita/lambda'

      - name: Execute jest
        run: |
          pnpm --filter @dekita/lambda test:cov

      - name: Jest coverage comment
        if: always()
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: server
          coverage-summary-path: ./apps/lambda/coverage/coverage-summary.json
          coverage-path: ./apps/lambda/coverage/coverage.txt
          junitxml-path: ./apps/lambda/coverage/junit.xml
